version: "3"
services:
  database:
    image: postgres


  migrate-up:
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./changes:/changes
    command: "-path /changes -database postgres://db_user:db_password@database:5432/db_name up"

  migrate-down:
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./changes:/changes
    command: "-path /changes -database postgres://db_user:db_password@database:5432/db_name down --all"

networks:
  network:
    driver: bridge
