name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch: 

env: 
  POSTGRES_DATABASE: teste-db
  
jobs:
  production:
    uses: ./.github/workflows/migrate.yml
    with:
      POSTGRES_USER: ${{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
      MIGRATION_COMMAND: ${{ env.MIGRATION_COMMAND }}
      POSTGRES_DATABASE: ${{ env.POSTGRES_DATABASE }}

