name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch:

jobs:
 # calling-migration-local:
 #       name: Call Migrate 
 #       uses: fabianofm1975/actions/.github/workflows/migration.yml@master

  calling-migration-stg:
        #needs: calling-migration-local
        name: Call Migrate 
        uses: fabianofm1975/actions/.github/workflows/migration.yml@master
        with:
          ENVIRONMENT: NonProduction-DB
        secrets: inherit

  calling-migration-prd:
        needs: calling-migration-stg
        name: Call Migrate 
        uses: fabianofm1975/actions/.github/workflows/migration.yml@master
        with:
          ENVIRONMENT: Production-DB
        secrets: inherit







