name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch: 

jobs:
  setting-variables-stg:
    runs-on: ubuntu-latest
    environment: NonProduction-DB
    steps:
      - name: Setting Environment
        run: echo "Setting envinronment..."
        env: 
          POSTGRES_DATABASE: teste-db
          MIGRATION_COMMAND: up
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  calling-migration-stg:
    needs: setting-variables-stg
    name: Call Migrate 
    uses: fabianofm1975/actions/.github/workflows/migration.yml@master
    with:
      POSTGRES_HOST: "$POSTGRES_HOST"
      POSTGRES_PORT: ${{ envi.POSTGRES_PORT }}
      POSTGRES_USER: $POSTGRES_USER 
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      MIGRATION_COMMAND: $MIGRATION_COMMAND
    secrets: 
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      







