name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch:

env: 
  POSTGRES_DATABASE: teste-db

jobs:
  calling-migration-local:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Start container - Run Database
            run: docker-compose -f "./docker-compose.yml" up -d database

          - name: Start container - Run Migrate UP
            run: docker-compose -f "./docker-compose.yml" up --abort-on-container-exit --exit-code-from migrate-up migrate-up

          - name: Start container - Run Migrate DOWN
            run: docker-compose -f "./docker-compose.yml" up --abort-on-container-exit --exit-code-from migrate-down-all migrate-down-all

          - name: Stop container
            run: docker-compose -f "./docker-compose.yml" down

  calling-migration-stg:
        needs: calling-migration-local
        name: Call Migrate - STG
        uses: fabianofm1975/actions/.github/workflows/migration.yml@master
        with:
          ENVIRONMENT: NonProduction-DB
        secrets: inherit

  calling-migration-prd:
        needs: calling-migration-stg
        name: Call Migrate - PRD
        uses: fabianofm1975/actions/.github/workflows/migration.yml@master
        with:
          ENVIRONMENT: Production-DB
        secrets: inherit







