name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch: 

env: 
  POSTGRES_DATABASE: teste-db
  MIGRATION_COMMAND: up
  
jobs:
  setting-variables-stg:
    runs-on: ubuntu-latest
    environment: NonProduction-DB
    steps:
      - name: Setting Environment
        run: echo "Setting envinronment..."









