name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch: 

env: 
  POSTGRES_DATABASE: teste-db
  MIGRATION_COMMAND: up
  
jobs:
  setting-variables-stg:
    runs-on: ubuntu-latest
    environment: NonProduction-DB
    steps:
      - name: Environment
        run: echo "Setting envinronment..."

  migration:
    name: Call Migrate 
    uses: ./.github/workflows/migrate.yml 
    with:
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }} 
      POSTGRES_DATABASE: ${{ env.POSTGRES_DATABASE }}
      MIGRATION_COMMAND: ${{ env.MIGRATION_COMMAND }}
    secrets:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}







