name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch:

jobs:
  calling-migration-stg:
        name: Call Migrate 
        uses: fabianofm1975/actions/.github/workflows/migration.yml@master
        with:
          POSTGRES_DATABASE: teste-db
          MIGRATION_COMMAND: up
          ENVIRONMENT: NonProduction-DB
        secrets: inherit







