name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch: 

env: 
  POSTGRES_DATABASE: teste-db
  MIGRATION_COMMAND: up
  
jobs:
  set-prod-vars:
    environment: Production-DB
    runs-on: ubuntu-latest
    outputs:
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Set Variables
        run: echo "Setting Varibles..."


  production-migration:
        needs: set-prod-vars
        uses: ./.github/workflows/migrate.yml 
        with:
          POSTGRES_DATABASE: $POSTGRES_DATABASE
          POSTGRES_HOST: $POSTGRES_HOST
          POSTGRES_PORT: $POSTGRES_PORT
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          MIGRATION_COMMAND: $MIGRATION_COMMAND




