name: DB Migrate
on: 
  push:
    branches: 
      - master
    paths:
      -  teste-db/migrations/changes
  pull_request:
    branches: 
      - master
    paths:
      -  teste-db/migrations/changes
  workflow_dispatch:

jobs:
  local-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1"
  staging-migrate:
    environment: NonProduction-DB
    needs: local-migrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Migrate
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: $${{ secrets.POSTGRES_PASSWORD}}
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_DATABASE: ${{ vars.POSTGRES_DATABASE }}
        uses: vovavc/migrate-github-action@v0.2.1
        with:
          path: ./teste-db/migrations/changes
          database: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?sslmode=disable
          command: $MIGRATE_COMMAND

  production-migrate:
    environment: Production-DB
    needs: [local-migrate,staging-migrate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: teste
        run:  echo ${{ vars.POSTGRES_HOST }} 
      - name: Migrate
        uses: vovavc/migrate-github-action@v0.2.1
        with:
          path: ./teste-db/migrations/changes
          database: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?sslmode=disable
          command: $MIGRATE_COMMAND
