name: DB Migrate
on: 
  push:
    branches: 
      - master
    paths:
      -  teste-db/migrations/changes
  pull_request:
    branches: 
      - master
    paths:
      -  teste-db/migrations/changes

jobs:
  local-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1"
  staging-migrate:
    needs: local-migrate
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1"
  production-migrate:
    needs: [local-migrate,staging-migrate]
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1"
  
