name: DB Migrate
on: 
  push:
    branches: 
      - master
    paths:
      -  teste-db/migrations/changes
  pull_request:
    branches: 
      - master
    paths:
      -  teste-db/migrations/changes
  workflow_dispatch:

jobs:
  local-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Local Migrate
        run: echo "To be implemented..."
  staging-migrate:
    environment: NonProduction-DB
    needs: local-migrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Migrate
        uses: vovavc/migrate-github-action@v0.2.1
        with:
          path: ./teste-db/migrations/changes
          database: postgres://${{ vars.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DATABASE }}
          command: ${{ vars.MIGRATE_COMMAND }}

  production-migrate:
    environment: Production-DB
    needs: [local-migrate,staging-migrate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Migrate
        uses: vovavc/migrate-github-action@v0.2.1
        with:
          path: ./teste-db/migrations/changes
          database: postgres://${{ vars.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DATABASE }}
          command: ${{ vars.MIGRATE_COMMAND }}
