name: DB Migrations Caller
on: 
  push:  
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch: 

env: 
  POSTGRES_DATABASE: teste-db
  
jobs:
  production:
    runs-on: ubuntu-latest
    name: Run production DB Migrations
    environment: Production-DB
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-file
        path: ${{ github.workspace }}
    - name: Run Migration
      uses: ./migrate.yml
      with:
        ARTIFACT_NAME: artifact-file
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
        MIGRATION_COMMAND: ${{ vars.MIGRATION_COMMAND }}
        POSTGRES_DATABASE: ${{ env.POSTGRES_DATABASE }}

