name: Manual Workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Ei cara, testando..."
      - name: Print good bye
        run: echo "Deu certo!"
