name: Run Migrations
on: 
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: Environment from which the variables will be set
        required: true
        type: string

jobs:
  migrate:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    name: Run DB Migration - ${{ inputs.ENVIRONMENT }}    
    container: 
      image: migrate/migrate
    steps:
      - name: Check if Environment is Local
        if: ${{ inputs.ENVIRONMENT }} == 'Local'
        run: echo "Local"
      - name: Check if Environment is NOT Local
        if: ${{ inputs.ENVIRONMENT }} != 'Local'
        uses: actions/checkout@v3      
        run: |
            echo "Not Local"
            echo ${{ inputs.ENVIRONMENT }}
            echo ${{ vars.MIGRATION_COMMAND }}
            echo ${{ vars.POSTGRES_DATABASE }}            
            echo ${{ vars.POSTGRES_HOST }}
            echo ${{ vars.POSTGRES_PORT }}
            echo ${{ vars.POSTGRES_USER }}
            migrate -verbose -path ${{ vars.POSTGRES_DATABASE }}/migrations/changes -database postgres://${{ vars.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DATABASE }} ${{ vars.MIGRATION_COMMAND }}