name: Migrations Template - teste-db 
on:   
  pull_request:
    types: [opened,synchronize,reopened,unlocked,closed]
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'
  workflow_dispatch:

jobs:
  calling-migration-local:        
        name: Call Migrate - Local
        uses: fabianofm1975/migrate/.github/workflows/run-local-migration.yml@master
        with:
          BASE_FOLDER: teste-db

  calling-migration-stg:
        if: github.event.pull_request.merged == true 
        needs: calling-migration-local
        name: Call Migrate - STG
        uses: fabianofm1975/migrate/.github/workflows/run-db-migration.yml@master
        with:
          ENVIRONMENT: NonProduction-DB
        secrets: inherit

  calling-migration-prd:
        if: github.event.pull_request.merged == true 
        needs: calling-migration-stg
        name: Call Migrate - PRD
        uses: fabianofm1975/migrate/.github/workflows/run-db-migration.yml@master
        with:
          ENVIRONMENT: Production-DB
        secrets: inherit
