name: Run Migrations
on: 
  workflow_call:


jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Run DB Migrations
    container: 
      image: migrate/migrate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Migrate
        run: migrate -verbose -path ${{ inputs.POSTGRES_DATABASE }}/migrations/changes -database postgres://${{ inputs.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ inputs.POSTGRES_HOST }}:${{ inputs.POSTGRES_PORT }}/${{ inputs.POSTGRES_DATABASE }} ${{ inputs.MIGRATION_COMMAND }}
