name: Run Migrations
on: 
  workflow_call:
    inputs:
      POSTGRES_DATABASE:
        description: Database´s where the migration will run
        required: true
     
jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Run DB Migrations
    container: 
      image: migrate/migrate
    steps:
      - name: Run Migrate
        run: migrate -path ${{ inputs.POSTGRES_DATABASE }}/migrations/changes -database postgres://${{ inputs.POSTGRES_USER }}:${{ inputs.POSTGRES_PASSWORD }}@${{ inputs.POSTGRES_HOST }}:${{ inputs.POSTGRES_PORT }}/${{ inputs.POSTGRES_DATABASE }} ${{ inputs.MIGRATION_COMMAND }}
