name: Migrations Template - teste-db 
on:   
  pull_request:
    types: [closed]
    branches: 
      - master
    paths:
      - 'teste-db/migrations/changes/*'

  pull_request_review:
    types: [submitted]

jobs:
  calling-migration-local: 
    if: github.event_name == 'pull_request_review' || github.event.pull_request.merged == true
    name: Call Migrate - Local
    uses: fabianofm1975/migrate/.github/workflows/run-local-migration.yml@master
    with:
        BASE_FOLDER: teste-db

  calling-migration-stg:
    if: github.event.pull_request.merged == true 
    needs: calling-migration-local
    name: Call Migrate - STG
    uses: fabianofm1975/migrate/.github/workflows/run-db-migration.yml@master
    with:
        ENVIRONMENT: teste-db-stg
    secrets: inherit

  calling-migration-prd: 
    if: calling-migration-local
    needs: calling-migration-stg
    name: Call Migrate - PRD
    uses: fabianofm1975/migrate/.github/workflows/run-db-migration.yml@master
    with:
        ENVIRONMENT: teste-db-prd
    secrets: inherit
