name: Push Workflow

on: push

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Echo a partir de push
        run: echo "Novo teste"
      - name: Checkout
        uses: actions/checkout@v3.5.2
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Teste
        run: echo "Teste second job"

