name: Run Local Migrations
on: 
  workflow_call:
    inputs:
      BASE_FOLDER:
        description: Database base folder
        required: true
        type: string

jobs:
  local-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start container - Run Database
        run: docker-compose -p ${{ inputs.BASE_FOLDER }} -f "./.github/dockerfile/docker-compose.yml" up -d database

      - name: Start container - Run Migrate UP
        run: echo "BASE_FOLDER=${{ inputs.BASE_FOLDER }}" > ${{ inputs.BASE_FOLDER }}.env && docker-compose --env-file ./${{ inputs.BASE_FOLDER }}.env -p ${{ inputs.BASE_FOLDER }} -f "./.github/dockerfile/docker-compose.yml" up --abort-on-container-exit --exit-code-from migrate-up migrate-up

      - name: Start container - Run Migrate DOWN
        run: echo "BASE_FOLDER=${{ inputs.BASE_FOLDER }}" > ${{ inputs.BASE_FOLDER }}.env && docker-compose --env-file ./${{ inputs.BASE_FOLDER }}.env -p ${{ inputs.BASE_FOLDER }} -f "./.github/dockerfile/docker-compose.yml" up --abort-on-container-exit --exit-code-from migrate-down-all migrate-down-all

      - name: Stop container
        run: docker-compose -p ${{ inputs.BASE_FOLDER }} -f "./.github/dockerfile/docker-compose.yml" down