name: Run Local Migrations
on: 
  workflow_call:
    inputs:
      BASE_FOLDER:
        description: Database base folder
        required: true
        type: string

jobs:
  local-migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: 
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 20

    name: Run DB Local Migration
    container: 
      image: migrate/migrate    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Migrate UP
        run: migrate -verbose -path ${{ inputs.BASE_FOLDER }}/migrations/changes -database postgres://postgres:postgres@postgres:5432/postgres?sslmode=prefer up

      - name: Run Migrate DOWN
        run: migrate -verbose -path ${{ inputs.BASE_FOLDER }}/migrations/changes -database postgres://postgres:postgres@postgres:5432/postgres?sslmode=prefer down
